voxpupuli/beaker-hostgenerator

lib/beaker-hostgenerator/cli.rb
lib/beaker-hostgenerator/data/vmpooler.rb
lib/beaker-hostgenerator/generator.rb

This PR ensures `ruby_arch` defaults to the correct value based on the Windows OS architecture as the setting is required to run puppet, facter and pxp-agent acceptance on Windows hosts, and allows the caller to request 32-bit Puppet on 64-bit Windows, e.g. `windows2012r2-6432a`. Windows is unique in that there are three combinations, and we currently support all three:
* 32-bit Puppet on 32-bit Windows
* 32-bit Puppet on 64-bit Windows
* 64-bit Puppet on 64-bit Windows

(QENG-3275) Add support for 32-bit puppet on 64-bit windows

---

lib/beaker-hostgenerator/data/vmpooler.rb

This reverts commit 3e36da18e7bfeec2fa92295fa5f9959d45611eb4.
I didn't notice until working on another ticket that this has a mismatched template platform value.

Revert "(QENG-3309) Add support for Cisco wrlinux-7"

---

lib/beaker-hostgenerator/data/vmpooler.rb

- Previous convention for Windows platforms is to always end in a -32
or -64.  There are some tests that rely on this naming scheme to
properly identify a 32-bit or 64-bit OS.
For instance, a Puppet acceptance test relies on that convention when
detecting the location of binaries per:
https://github.com/puppetlabs/puppet/blob/master/acceptance/tests/ensure_puppet-agent_paths.rb#L140-L143
Original commit that introduced these was
3d1be3833b0dd95d508d89ecbe76464524f578c3

(maint) Update Windows 10 platform names

---

CHANGELOG.md
lib/beaker-hostgenerator/data/vmpooler.rb

Need support for Cisco Virtrual Routing & Forwarding (VRF) as well as to use 'beaker' as the ssh username for Cisco NXOS

(maint) Add better support for Cisco platforms

---

lib/beaker-hostgenerator/data/vmpooler.rb
test/fixtures/default/cisconx-64a
test/fixtures/default/ciscoxr-64u
test/fixtures/default/ubuntu1604-32u
test/fixtures/default/ubuntu1604-64l
test/fixtures/osinfo-version-0/cisconx-64a
test/fixtures/osinfo-version-0/ciscoxr-64u
test/fixtures/osinfo-version-0/ubuntu1604-32u
test/fixtures/osinfo-version-0/ubuntu1604-64l
test/fixtures/osinfo-version-1/cisconx-64a
test/fixtures/osinfo-version-1/ciscoxr-64u
test/fixtures/osinfo-version-1/ubuntu1604-32u
test/fixtures/osinfo-version-1/ubuntu1604-64l

This PR also
* fixes some test fixture borkage that resulted from the Cisco platform renames
* adds new test fixtures (it's not clear why these weren't in place previously)

(QENG-3489) Add Ubuntu 16.04 to beaker host generator data.

---

CHANGELOG.md
README.md
lib/beaker-hostgenerator/cli.rb
lib/beaker-hostgenerator/data.rb
lib/beaker-hostgenerator/generator.rb
lib/beaker-hostgenerator/hypervisor.rb
lib/beaker-hostgenerator/hypervisor/none.rb
lib/beaker-hostgenerator/hypervisor/vmpooler.rb
lib/beaker-hostgenerator/parser.rb
lib/beaker-hostgenerator/roles.rb
lib/beaker-hostgenerator/util.rb
spec/beaker-hostgenerator/generator_spec.rb
spec/beaker-hostgenerator/parser_spec.rb
test/fixtures/per-host-settings/arbitrary-settings.yaml
test/fixtures/per-host-settings/every-hypervisor.yaml
test/fixtures/per-host-settings/malformed-input.yaml

This commit adds a new "none" hypervisor to support non-provisioned
hosts. Non-provisioned hosts require a handful of other host settings to
be specified in order for Beaker to use it properly, so this commit also
adds support for arbitrary key-value host settings.
For example:
```
$ .. centos6-64m{hypervisor=none,hostname=my-host,vmhostname=othername}
---
HOSTS:
my-host:
pe_dir:
pe_ver:
pe_upgrade_dir:
pe_upgrade_ver:
platform: el-6-x86_64
hypervisor: none
vmhostname: othername
roles:
- agent
- master
CONFIG:
nfs_server: none
consoleport: 443
```

(QENG-3276) Add None hypervisor and per-host settings support

---

README.md
lib/beaker-hostgenerator/cli.rb
lib/beaker-hostgenerator/generator.rb
test/fixtures/per-host-settings/with-global-settings.yaml

This commit adds CLI support for specifying global configuration
settings that will be included in the CONFIG section.
For example:
```
$ beaker-hostgenerator --global-config {master=headless} redhat7-64m
```
```yaml
---
HOSTS:
redhat7-64-1:
pe_dir:
pe_ver:
pe_upgrade_dir:
pe_upgrade_ver:
hypervisor: vmpooler
platform: el-7-x86_64
template: redhat-7-x86_64
roles:
- agent
- master
CONFIG:
nfs_server: none
consoleport: 443
master: headless
pooling_api: http://vmpooler.delivery.puppetlabs.net/
```

(QENG-3920) Global host config CLI configuration support

---

lib/beaker-hostgenerator/cli.rb
test/test_cli.rb
test/test_stdout.rb

This commit adds a -v/--version CLI flag to print the version number.
This also refactors the flow-of-control to remove the need for the
SafeEarlyExit exception by moving all output-generating codepaths out of
the initialize method and into the execute method, and teasing apart the
--list and default generation codepaths. The execute method
now chooses the code path based on the CLI options set in initialize.
While we no longer throw a SafeEarlyExit exception, it's effectively
part of the API so we must wait until the appropriate time/release to
delete it. Existing usages of it should not be broken with the changes
in this commit.

(QENG-3377) Add --version CLI flag

---

lib/beaker-hostgenerator/parser.rb
spec/beaker-hostgenerator/parser_spec.rb

This commit adds support for uppercase-only alphanumeric architecture
bits in platform names. For example, we now support "POWER" or "POWER7"
instead of just "32" or "64".
Uppercase letters allow for backwards compatibility when roles are
specified, which come after the architecture bit. This implementation
relies on the fact that the role and arbitrary role characters are
only lowercase.
This allows us to distinguish between the architecture "POWER" and the
role "m" when parsing the spec "POWERm", as in "aix71-POWERm".

(QENG-3808) Support uppercase alphanumeric architectures

---

README.md
lib/beaker-hostgenerator/cli.rb
lib/beaker-hostgenerator/hypervisor.rb
lib/beaker-hostgenerator/hypervisor/unknown.rb
test/fixtures/per-host-settings/arbitrary-hypervisor.yaml

This commit allows unknown hypervisors to be specified by the user.
Previously, if the hypervisor specified by the user was not one of the
valid, built-in implementations then an error was thrown notifying the
user that an invalid hypervisor was requested.
Now, this is no longer an error, and instead the host generation will
continue as normal but there will be no hypervisor-specific
configuration. The name of the unknown hypervisor will be the value of
the hypervisor configuration of the hosts.
To implement this, we can repurpose the special `Hypervisor::None`
implementation to instead represent an unknown (but equally valid)
hypervisor. The unknown name will now be the value of `hypervisor` in
the generated config, where it used to be `hypervisor: none`.
For example:
```bash
$ .. …
```

(QENG-3946) Support arbitrary hypervisors

---

README.md
lib/beaker-hostgenerator/generator.rb
lib/beaker-hostgenerator/parser.rb
spec/beaker-hostgenerator/parser_spec.rb
test/fixtures/per-host-settings/url-encoded.yaml

This commit adds a "pre-processing" step to the Parser that will always
attempt to URL-decode the input before parsing it. This behavior is
necessary to support specifying arbitrary settings in the input string
when the input ends up as part of an HTTP URL, such as almost every
usage we currently have in Jenkins.

(QENG-4034) Automatically URL-decode raw input

---

lib/beaker-hostgenerator/data.rb
test/fixtures/generated/default/osx1012-64m
test/fixtures/generated/default/windows2016-6432m
test/fixtures/generated/default/windows2016-64f
test/fixtures/generated/multiplatform/centos5-64aulcdfm-windows2016-6432-centos5-64a
test/fixtures/generated/multiplatform/centos6-32a-windows2016-64-centos6-32aulcdfm
test/fixtures/generated/multiplatform/osx1012-64m-sles10-32-osx1012-64u
test/fixtures/generated/multiplatform/osx1012-64m-sles11-32-osx1012-64u
test/fixtures/generated/multiplatform/sles10-32f-osx1012-64-sles10-32l
test/fixtures/generated/multiplatform/sles11-32aulcdfm-osx1012-64-sles11-32a
test/fixtures/generated/multiplatform/windows2016-6432m-centos5-64-windows2016-6432u
test/fixtures/generated/multiplatform/windows2016-64f-centos6-32-windows2016-64l
test/fixtures/generated/osinfo-version-0/osx1012-64m
test/fixtures/generated/osinfo-version-0/windows2016-6432m
test/fixtures/generated/osinfo-version-0/windows2016-64f
test/fixtures/generated/osinfo-version-1/osx1012-64m
test/fixtures/generated/osinfo-version-1/windows2016-6432m
test/fixtures/generated/osinfo-version-1/windows2016-64f

Added OSX 10.12 (Sierra) and Windows Server 2016 to supported beaker-hostgenerator platforms

(QENG-4176 & QENG-4180) Add OSX 10.12 and Windows 2016

---

README.md
lib/beaker-hostgenerator/hypervisor.rb
lib/beaker-hostgenerator/hypervisor/abs.rb
test/fixtures/per-host-settings/every-hypervisor.yaml

This commit adds a new hypervisor called 'abs' that will support
generating configurations necessary for working with CI.next and the
AlwaysBeScheduling service.
Currently, the behavior of the abs hypervisor is basically the same as
the vmpooler hypervisor. The only difference is it doesn't fixup the
nodes to support old PE versions.
Having a built-in hypervisor for ABS alleviates the need for users to
manually override the hypervisor key on each node.

(QENG-4204) Add AlwaysBeScheduling hypervisor

---

lib/beaker-hostgenerator/abs-support.rb
lib/beaker-hostgenerator/cli.rb
lib/beaker-hostgenerator/generator.rb
spec/beaker-hostgenerator/abs-support_spec.rb

This adds a CLI switch '--templates-only' that will reduce the generated
output to include only the template values from the HOSTS.

(QENG-4204) Add CLI flag to only generate templates

---

lib/beaker-hostgenerator/abs-support.rb
lib/beaker-hostgenerator/cli.rb
spec/beaker-hostgenerator/abs-support_spec.rb

Previously the --templates-only switch would output a custom CSV-style
format, plus it repeated platforms rather than tallying them up.
This commit changes the output format to be a JSON map, with the
platforms as keys and the total counts as values.

(QENG-4407) Return proper JSON map

---

lib/beaker-hostgenerator/abs-support.rb
lib/beaker-hostgenerator/cli.rb
spec/beaker-hostgenerator/abs-support_spec.rb

We've been using these `cinext` branch changes for a few weeks now during CI.next development.
We're ready to merge into `master` and cut a gem release so we can stop pinning projects to the `cinext` branch on GitHub and just have them depend on the new gem release like normal.

Merge CI.next branch into master

---

README.md
lib/beaker-hostgenerator/generator.rb
lib/beaker-hostgenerator/parser.rb
spec/beaker-hostgenerator/parser_spec.rb
test/fixtures/per-host-settings/with-global-settings.yaml

Previously all whitespace was automatically removed from all input. This
commit removes that behavior, allowing for values with whitespace in
them to be properly generated.
This change means users are responsible for properly quoting, escaping,
or URL-encoding the whitespace as necessary.

(BKR-934) Allow for whitespace in settings

---

.gitignore
beaker-hostgenerator.gemspec

This project has a TON of test fixtures that are not necessary in production,
yet we were still bundling them into the gem.
We don't need to include any of these, they were just making the resulting gem
significantly larger.

(MAINT) Exclude test files from built gem

---

beaker-hostgenerator.gemspec

This gemspec directive `test_files` will cause the files it references to be
included in the built gem so they can be used during the `gem test` command.
We do not intend to support the ability for users to run `gem test`, and
furthermore this gem subcommand doesn't even exist anymore.

(MAINT) Delete test_files directive to keep fixtures out of the gem

---

Gemfile
Rakefile
acceptance/config/nodes/vagrant-ubuntu-1404.yml
acceptance/tests/first.rb
beaker-hostgenerator.gemspec

This deletes everything related to acceptance testing.
We had no tests, and we have no intentions of adding any. We started to lay out
the groundwork for acceptance testing a while ago with the "acceptance/"
directory, `beaker` test dependency, and the `acceptance` Rake task.
This commit deletes that groundwork, as it is out of date and just getting in
the way at this point.  If we decide to add acceptance tests in the future, it
will likely look different than this anyway.

(MAINT) Remove acceptance testing

---

lib/beaker-hostgenerator/data.rb
test/fixtures/generated/default/fedora25-32c
test/fixtures/generated/default/fedora25-64d
test/fixtures/generated/multiplatform/fedora25-32c-ubuntu1004-32-fedora25-32d
test/fixtures/generated/multiplatform/fedora25-64d-solaris112-64-fedora25-64c
test/fixtures/generated/multiplatform/solaris112-64f-fedora25-64-solaris112-64l
test/fixtures/generated/multiplatform/ubuntu1004-32m-fedora25-32-ubuntu1004-32u
test/fixtures/generated/osinfo-version-0/fedora25-32c
test/fixtures/generated/osinfo-version-0/fedora25-64d
test/fixtures/generated/osinfo-version-1/fedora25-32c
test/fixtures/generated/osinfo-version-1/fedora25-64d

Added fedora 25 platforms for i386 and x86_64. The test fixtures were created by running rake generate:fixtures.

Add Fedora 25 platforms and test fixtures

---

lib/beaker-hostgenerator/data.rb
test/fixtures/generated/default/ubuntu1610-32l
test/fixtures/generated/default/ubuntu1610-64c
test/fixtures/generated/multiplatform/fedora19-64a-ubuntu1610-64-fedora19-64aulcdfm
test/fixtures/generated/multiplatform/fedora20-32u-ubuntu1610-32-fedora20-32m
test/fixtures/generated/multiplatform/ubuntu1610-32l-fedora20-32-ubuntu1610-32f
test/fixtures/generated/multiplatform/ubuntu1610-64c-fedora19-64-ubuntu1610-64d
test/fixtures/generated/osinfo-version-0/ubuntu1610-32l
test/fixtures/generated/osinfo-version-0/ubuntu1610-64c
test/fixtures/generated/osinfo-version-1/ubuntu1610-32l
test/fixtures/generated/osinfo-version-1/ubuntu1610-64c

Added Ubuntu 16.10 platforms for i386 and x86_64. The test fixtures were created by running rake generate:fixtures.

Add Ubuntu 16.10 platforms and test fixtures

---

lib/beaker-hostgenerator/cli.rb
spec/beaker-hostgenerator/generator_spec.rb
test/util/generator_helpers.rb

This warning message was added a while ago to inform users of an upcoming
breaking change. We're no longer certain that we'll be making the breaking
change though, so the warning is a bit misleading.
Furthermore, we're now trying to silence this message when beaker-hostgenerator
is used programatically within Beaker.
There will likely be more changes that are outlined in the linked ticket, such
as adding a new CLI switch to toggle between specific & generic platform names.

(QENG-4019) Remove warning message about changing defaults

---

lib/beaker-hostgenerator/data.rb
test/fixtures/generated/default/windows2012r2_wmf5-64l
test/fixtures/generated/multiplatform/centos7-64c-windows2012r2_wmf5-64-centos7-64d
test/fixtures/generated/multiplatform/windows2012r2_wmf5-64l-centos7-64-windows2012r2_wmf5-64f
test/fixtures/generated/osinfo-version-0/windows2012r2_wmf5-64l
test/fixtures/generated/osinfo-version-1/windows2012r2_wmf5-64l

This commit adds the win-2012r2-wmf5-x86_64 vmpooler image, which is a variation
on the Windows Sever 2012R2 64bit image.

(MODULES-4667) Add Windows 2012R2 WMF5 VMPooler image

---

lib/beaker-hostgenerator/generator.rb
lib/beaker-hostgenerator/hypervisor/vmpooler.rb
test/fixtures/per-host-settings/with-global-settings-overwrite.yaml

Before this change the code would pull and merge the hypervisor defaults on top of any
user provided --global-config block. This reverses the logic to use defaults only
if the key is not specified in the --global-config section. This specifically
enables overwritting the pooling_api for the vmpooler hypervisor, as it is the
only one with a default global_config() method implementation. Also added it's
respective test

(maint) The hypervisor defaults are not overwritable

---

lib/beaker-hostgenerator/data.rb
test/fixtures/generated/default/vro6-64f
test/fixtures/generated/default/vro7-64m
test/fixtures/generated/multiplatform/vro6-64f-fedora20-32-vro6-64l
test/fixtures/generated/multiplatform/vro7-64m-fedora19-64-vro7-64u
test/fixtures/generated/osinfo-version-0/vro6-64f
test/fixtures/generated/osinfo-version-0/vro7-64m
test/fixtures/generated/osinfo-version-1/vro6-64f
test/fixtures/generated/osinfo-version-1/vro7-64m

This adds both `vro-6-x86_64` and `vro-7-x86_64`. The templates already exist within vmpooler.
@nwolfe

(QENG-5041) Add vRO to support platforms

---

README.md
lib/beaker-hostgenerator/cli.rb
lib/beaker-hostgenerator/generator.rb
lib/beaker-hostgenerator/parser.rb
spec/beaker-hostgenerator/parser_spec.rb

Before, we had no way to add lists to configurations. This adds a new bracket in order to parse out any lists the user may want to add in.
@nwolfe @eputnam

(QENG-4945) Add support for arbitrary lists

---

README.md
lib/beaker-hostgenerator/generator.rb
lib/beaker-hostgenerator/parser.rb
spec/beaker-hostgenerator/parser_spec.rb

Previous to this commit, the hostgenerator was restricted to shallow
hashes and arrays that could be conveyed in BHG syntax. This commit now
allows for arbitrary nesting of those data structures.

(QENG-5128) Add arbitrary hash and array support

---

lib/beaker-hostgenerator/cli.rb
lib/beaker-hostgenerator/data.rb
spec/beaker-hostgenerator/abs_support_spec.rb
test/fixtures/generated/osinfo-version-0/redhat7-POWERl
test/fixtures/generated/osinfo-version-0/ubuntu1604-POWERd
test/fixtures/generated/osinfo-version-1/redhat7-POWERl
test/fixtures/generated/osinfo-version-1/ubuntu1604-POWERd

Note: I was a bit surprised to find that the test fixtures generated used 'vmpooler' for the hypervisor, but I checked and this is also the case for other ABS platforms, e.g, AIX 7.2. So I'm assuming this is not a problem.

(IMAGES-497) Add support for Power8 Ubuntu 16.04 and RHEL 7

---

lib/beaker-hostgenerator/data.rb
spec/beaker-hostgenerator/abs_support_spec.rb
test/fixtures/generated/osinfo-version-0/redhat7-POWERl
test/fixtures/generated/osinfo-version-1/redhat7-POWERl

I've changed the RHEL 7.3 Power8 platform name in
hardware-infrastructure from 'rhel' to 'redhat' in order to follow the
existing naming conventions in beaker. 
This will help fix "unrecognized platform name" errors when trying to enable automated testing for this platform without having to make further changes in beaker.

(BKR-1166) Rename rhel platform/template to redhat

---

lib/beaker-hostgenerator/data.rb
test/fixtures/generated/osinfo-version-0/redhat7-POWERl
test/fixtures/generated/osinfo-version-0/ubuntu1604-POWERd
test/fixtures/generated/osinfo-version-1/redhat7-POWERl
test/fixtures/generated/osinfo-version-1/ubuntu1604-POWERd

My previous work on BHG to enable Power8 testing was based on some misconceptions, which I believe I've finally resolved. These platform definitions work with manual runs of beaker I've been able to test locally. Furthermore, there needs to be a discrepancy between the platform definition and the template definition for this to work with hwi that I've worked out with @McdonaldSeanp. 
Note: that's not a typo, Redhat calls their Power8 platform arch 'ppc64le' and Debian/Ubuntu call it 'ppc64el'. Go figure.

Another round of Power8 changes

---

lib/beaker-hostgenerator/data.rb
lib/beaker-hostgenerator/util.rb
spec/beaker-hostgenerator/generator_spec.rb
spec/spec_helper.rb

(PE-21479) Rewrite pe_dir() to provide rc builds ￼…
...and to determine build source just from the pe_version format.
Previously, source was either archives/releases if version and family
were the exact same string, otherwise ci-ready.
Recently we have added archives/internal which houses rc tagged builds
long term (ci-ready has a two-week life span).  These internal archive
releases let us test rc builds for internal consumption, but introduced
a third source.
Fourth source, actually, I'd forgotten that we already had dev version
strings with PEZ in them that need to be sourced from
feature/ci-ready...
The patch bases everything off the version because the four cases are
mutually exclusive, and the previous determination of a release source
based on version == family doesn't make sense …

(PE-21479) Rewrite pe_dir() to provide rc/pez builds from pe_version

---

lib/beaker-hostgenerator/data.rb
spec/beaker-hostgenerator/generator_spec.rb

Missed this case, which errors out because we end giving a nil
substitution to sprintf.
Also tighten up the case of an unparseable version string to return ''.

(PE-21479) Return nil if version is an empty string

---

lib/beaker-hostgenerator/data.rb
test/fixtures/generated/default/cisconxhw-64f
test/fixtures/generated/multiplatform/cisconxhw-64f-windows2012r2-64-cisconxhw-64l
test/fixtures/generated/osinfo-version-0/cisconxhw-64f
test/fixtures/generated/osinfo-version-1/cisconxhw-64f

This commit adds data for cisconxhw to allow the use of hardware hosts (the
actual physical switches) when desired.

(maint) Add cisconxhw data

---

lib/beaker-hostgenerator/data.rb

Add Beaker Host Generator definitions for:
1. Windows-2012r2-core-x86_64
2. Windows-2016-core-x86_64
Although these platforms are now on vmpooler, pipelines can't use them
without hostgenerator definitions.

(IMAGES-614) Add Windows 2012r2/2016 Core defs

---

lib/beaker-hostgenerator/data.rb
test/fixtures/generated/default/amazon6-64d
test/fixtures/generated/multiplatform/amazon6-64d-windows81-64-amazon6-64c
test/fixtures/generated/osinfo-version-0/amazon6-64d
test/fixtures/generated/osinfo-version-1/amazon6-64d

Previously, this was trying to download and install PE based on the "amazon"
platform when it really needs to be using the el-6 package. Fixing to match
expected packages.

(maint) Fix platform and packaging_platform for amazon6

---

lib/beaker-hostgenerator/data.rb

centos-7-arm64 is the correct name of the target in NSpooler.
Since the abs templates are not used in the generated test fixtures, there are no updates to the fixtures with this change.

(BKR-1233) Update abs template string for AARCH64

---

lib/beaker-hostgenerator/data.rb

Note - the Administrator Username has to be localised for beaker runs
for this platform, so the user attribute is also supplied for the
hosts.yaml file.

(IMAGES-335) Add Windows 2012r2 French

---

lib/beaker-hostgenerator/data.rb
test/fixtures/generated/default/amazon7-64f
test/fixtures/generated/multiplatform/amazon7-64f-windows8-64-amazon7-64l
test/fixtures/generated/multiplatform/windows8-64u-amazon7-64-windows8-64m
test/fixtures/generated/osinfo-version-0/amazon7-64f
test/fixtures/generated/osinfo-version-1/amazon7-64f

Amazon Linux v2 is based on el-7-x86_64, and is not packaged as a separate platform - it uses the el-7 package.

(BKR-1308) Add support for amazon7 (Amazon Linux v2)

---

lib/beaker-hostgenerator/data.rb
test/fixtures/generated/default/redhatfips7-64aulcdfm
test/fixtures/generated/multiplatform/redhatfips7-64aulcdfm-sles10-32-redhatfips7-64a
test/fixtures/generated/multiplatform/sles10-32a-redhatfips7-64-sles10-32aulcdfm
test/fixtures/generated/osinfo-version-0/redhatfips7-64aulcdfm
test/fixtures/generated/osinfo-version-1/redhatfips7-64aulcdfm

In order for Beaker to not have to know about all flavors of each OS, we should use el-7-x86_64 as the mapping for the platform and packaging_platform.

(maint) Correct the new fips platform to use el-7 as the platform

---

lib/beaker-hostgenerator/data.rb
test/fixtures/generated/default/redhatfips7-64aulcdfm
test/fixtures/generated/multiplatform/redhatfips7-64aulcdfm-sles10-32-redhatfips7-64a
test/fixtures/generated/multiplatform/sles10-32a-redhatfips7-64-sles10-32aulcdfm
test/fixtures/generated/osinfo-version-0/redhatfips7-64aulcdfm
test/fixtures/generated/osinfo-version-1/redhatfips7-64aulcdfm

This change is being made in puppet-agent and related dependencies in
order to make this platform usable in pe_repo.

(PA-1958) Rename redhat-fips packaging_platform to redhatfips

---

lib/beaker-hostgenerator/data.rb

Windows Server 2019 Preview pools have been added to vmpooler so add a
beaker-hostgenerator definition.

(IMAGES-843) Add Windows Server 2019 Definitions

---

lib/beaker-hostgenerator/data.rb

beaker uses ss to determine open ports/sockets within virtual instances.
ss is provided by iproute2, which isn't installed by default in the
docker containers.

install iproute2 on ubuntu18.04

---

lib/beaker-hostgenerator/data.rb

Windows 2019 Core is being added to the pooler, so a new
beaker-hostgenerater is needed.

(IMAGES-954) Add win-2019-core-x86_64

---

lib/beaker-hostgenerator/data.rb
test/fixtures/per-host-settings/every-hypervisor.yaml

beaker-docker must run containers in privileged mode with an /sbin/init
entrypoint to successfully simulate a full operating sytem. This
combination can cause the container to open virutal consoles on the host
machine. These getty processes regularly consume 100% of CPU; they are
not automatically killed when the container is destroyed, and must be
cleaned up manually.
tty1 getty services were already disabled as part of the default set of
image commands for docker platforms, but this did not prevent the
behavior for other ttys. Replacing the getty executable with a copy of
/bin/true successfully disables all of them.
https://github.com/moby/moby/issues/4040 describes this issue and the workaround (and mentions beaker-docker explicitly).

(BKR-1548) Totally disable getty when using docker

---

lib/beaker-hostgenerator/data.rb
lib/beaker-hostgenerator/hypervisor.rb
lib/beaker-hostgenerator/hypervisor/vagrant.rb
test/fixtures/per-host-settings/every-hypervisor.yaml

This also adds some base boxes based from the Vagrant Cloud.
Official builds are used for CentOS and Fedora in a generated way. For
Debian Wheezy, Jessie and Stretch 64 bits we also use the official
builds but manually since there's no automated way to map numbers to
releases. For all other platforms we rely on the generic builds which
uses the same naming scheme as our host specs.
We could use the official Ubuntu images in the same way as Debian, but
they're only built for Virtualbox where the generic ones are built for
other provides as well.
This PR is currently here for initial feedback and testing. I know I'll
need to add tests but an initial pass would be appreciated.

Add a vagrant hypervisor

---

lib/beaker-hostgenerator/hypervisor.rb
lib/beaker-hostgenerator/hypervisor/abs.rb
lib/beaker-hostgenerator/hypervisor/docker.rb
lib/beaker-hostgenerator/hypervisor/unknown.rb
lib/beaker-hostgenerator/hypervisor/vagrant.rb
lib/beaker-hostgenerator/hypervisor/vmpooler.rb
test/fixtures/per-host-settings/vagrant-hypervisor.yaml

Previously the options[:hypervisor] did not end up in the hosts' config.  This refactors the hypervisors in a common method which always copies the original name into the resulting host config. It still prefers the explicit host hypervisor over the command line option.

(maint) Fix --hypervisor vagrant_libvirt

---

lib/beaker-hostgenerator/data.rb
test/fixtures/generated/multiplatform/amazon7-ARM64m-windows7-64-amazon7-ARM64u
test/fixtures/generated/osinfo-version-0/amazon7-ARM64m
test/fixtures/generated/osinfo-version-1/amazon7-ARM64m

There is no platform(el-7-arm64) defined in puppet so we cannot build on that.
Build the packages for amazon7-ARM64 on el-7-aarch64 and test them on amazon7-ARM64.
I still need an opinion on this. Does it look ok?
adhoc build: https://jenkins-platform.delivery.puppetlabs.net/view/Adhoc/job/platform_puppet-agent-extra_puppet-agent-integration-suite_adhoc-ad_hoc/518/

(PA-2387) use el-7-aarch64 as platform for amazon7-ARM64

---

lib/beaker-hostgenerator/data.rb

This commit adds support for Cisco ios and iosxe devices. Without this change beaker-hostgenerator does not support these devices.

(QENG-6980) Add support for Cisco ios

---

lib/beaker-hostgenerator/data.rb
test/fixtures/generated/default/ciscoiosc2960-ARM32u
test/fixtures/generated/default/ciscoiosc3750-ARM32l
test/fixtures/generated/default/ciscoiosc4507r-ARM32c
test/fixtures/generated/default/ciscoiosc4948-ARM32d
test/fixtures/generated/default/ciscoiosc6503-ARM32f
test/fixtures/generated/default/ciscoiosxec3605-ARM32m
test/fixtures/generated/default/ciscoiosxec4503-ARM32aulcdfm
test/fixtures/generated/multiplatform/ciscoiosc2960-ARM32u-windows2012r2_core-6432-ciscoiosc2960-ARM32m
test/fixtures/generated/multiplatform/ciscoiosc3750-ARM32l-windows2012r2_core-64-ciscoiosc3750-ARM32f
test/fixtures/generated/multiplatform/ciscoiosc4507r-ARM32c-windows2012r2_fr-6432-ciscoiosc4507r-ARM32d
test/fixtures/generated/multiplatform/ciscoiosc4948-ARM32d-windows2012r2_fr-64-ciscoiosc4948-ARM32c
test/fixtures/generated/multiplatform/ciscoiosc6503-ARM32f-windows2012r2_ja-6432-ciscoiosc6503-ARM32l
test/fixtures/generated/multiplatform/ciscoiosxec3605-ARM32m-windows2012r2_ja-64-ciscoiosxec3605-ARM32u
test/fixtures/generated/multiplatform/ciscoiosxec4503-ARM32aulcdfm-windows2012r2_wmf5-64-ciscoiosxec4503-ARM32a
test/fixtures/generated/osinfo-version-0/ciscoiosc2960-ARM32u
test/fixtures/generated/osinfo-version-0/ciscoiosc3750-ARM32l
test/fixtures/generated/osinfo-version-0/ciscoiosc4507r-ARM32c
test/fixtures/generated/osinfo-version-0/ciscoiosc4948-ARM32d
test/fixtures/generated/osinfo-version-0/ciscoiosc6503-ARM32f
test/fixtures/generated/osinfo-version-0/ciscoiosxec3605-ARM32m
test/fixtures/generated/osinfo-version-0/ciscoiosxec4503-ARM32aulcdfm
test/fixtures/generated/osinfo-version-1/ciscoiosc2960-ARM32u
test/fixtures/generated/osinfo-version-1/ciscoiosc3750-ARM32l
test/fixtures/generated/osinfo-version-1/ciscoiosc4507r-ARM32c
test/fixtures/generated/osinfo-version-1/ciscoiosc4948-ARM32d
test/fixtures/generated/osinfo-version-1/ciscoiosc6503-ARM32f
test/fixtures/generated/osinfo-version-1/ciscoiosxec3605-ARM32m
test/fixtures/generated/osinfo-version-1/ciscoiosxec4503-ARM32aulcdfm

Before, these were all managed by one pool. These need to be called
individually based on their version number so there are now
separate calls for each version for cisco ios.
Additionally, made it clear that these are ARM32 hardware devices.

(QENG-7134) Individualize cisco IOS platforms

---

lib/beaker-hostgenerator/data.rb
test/fixtures/generated/default/fedora30-64aulcdfm
test/fixtures/generated/multiplatform/fedora30-64aulcdfm-ubuntu1204-64-fedora30-64a
test/fixtures/generated/multiplatform/ubuntu1204-64u-fedora30-64-ubuntu1204-64m
test/fixtures/generated/osinfo-version-0/fedora30-64aulcdfm
test/fixtures/generated/osinfo-version-1/fedora30-64aulcdfm

(IMAGES-1116) Add beaker-hostgenerator support for Fedora 30 (amd64)

---

lib/beaker-hostgenerator/data.rb
test/fixtures/generated/default/ciscoiosxec3650-ARM32m
test/fixtures/generated/multiplatform/ciscoiosxec3650-ARM32m-windows2012r2_ja-64-ciscoiosxec3650-ARM32u
test/fixtures/generated/osinfo-version-0/ciscoiosxec3650-ARM32m
test/fixtures/generated/osinfo-version-1/ciscoiosxec3650-ARM32m

This commit fixes the name of the Cisco c3650 device from 3605. Without this change there is no hostgenerator data for c3650.

(QENG-6980) Fix name for c3650

---

lib/beaker-hostgenerator/data.rb

This commit adds the version number to OS templates for Cisco ios and iosxe devices. Without this change the template reference is invalid.

(QENG-6980) Add OS version to template

---

lib/beaker-hostgenerator/roles.rb

This adds support for the new 'pe_compiler' role, which is a compile master with PuppetDB, by including the existing compile_master configuration when pe_compiler is specified.
Should be merged with https://github.com/puppetlabs/beaker-pe/pull/144 and https://github.com/puppetlabs/beaker-pe-large-environments/pull/30.

(PE-26509) Add support for pe_compiler role

---

lib/beaker-hostgenerator/data.rb

For the moment it looks to be impossible to run acceptance with Beaker on Debian10 and Docker :
https://travis-ci.org/voxpupuli/puppet-letsencrypt/jobs/564849203#L1208
The command `wget` used to get the `puppet-agent` is not present.
This PR add a section `docker_image_commands` to Debian10.
I removed `systemd-sysv` i suppose it is not useful now.

Add docker_image_commands to debian10 with docker

---

lib/beaker-hostgenerator/data.rb
test/fixtures/generated/default/windows2012r2_ja-6432l
test/fixtures/generated/default/windows2012r2_ja-64u
test/fixtures/generated/default/windows2016_fr-6432f
test/fixtures/generated/default/windows2016_fr-64d
test/fixtures/generated/default/windows2019_fr-6432f
test/fixtures/generated/default/windows2019_fr-64c
test/fixtures/generated/default/windows2019_ja-6432f
test/fixtures/generated/default/windows2019_ja-64c
test/fixtures/generated/multiplatform/centos5-64c-windows2016_fr-6432-centos5-64d
test/fixtures/generated/multiplatform/centos6-32d-windows2016_fr-64-centos6-32c
test/fixtures/generated/multiplatform/centos6-32u-windows2012r2_ja-6432-centos6-32m
test/fixtures/generated/multiplatform/centos6-64l-windows2012r2_ja-64-centos6-64f
test/fixtures/generated/multiplatform/ciscoiosc4507r-ARM32c-windows2012r2_fr-6432-ciscoiosc4507r-ARM32d
test/fixtures/generated/multiplatform/ciscoiosc4948-ARM32d-windows2012r2_fr-64-ciscoiosc4948-ARM32c
test/fixtures/generated/multiplatform/ciscoiosc6503-ARM32f-windows2012r2_ja-6432-ciscoiosc6503-ARM32l
test/fixtures/generated/multiplatform/ciscoiosxec3650-ARM32m-windows2012r2_ja-64-ciscoiosxec3650-ARM32u
test/fixtures/generated/multiplatform/windows2012r2_ja-6432l-centos6-32-windows2012r2_ja-6432f
test/fixtures/generated/multiplatform/windows2012r2_ja-64u-centos6-64-windows2012r2_ja-64m
test/fixtures/generated/multiplatform/windows2016_fr-6432f-centos5-64-windows2016_fr-6432l
test/fixtures/generated/multiplatform/windows2016_fr-64d-centos6-32-windows2016_fr-64c
test/fixtures/generated/osinfo-version-0/windows2012r2_ja-6432l
test/fixtures/generated/osinfo-version-0/windows2012r2_ja-64u
test/fixtures/generated/osinfo-version-0/windows2016_fr-6432f
test/fixtures/generated/osinfo-version-0/windows2016_fr-64d
test/fixtures/generated/osinfo-version-1/windows2012r2_ja-6432l
test/fixtures/generated/osinfo-version-1/windows2012r2_ja-64u
test/fixtures/generated/osinfo-version-1/windows2016_fr-6432f
test/fixtures/generated/osinfo-version-1/windows2016_fr-64d

This is an outcome of moving the Windows-2012r2 localised vmpooler platforms to Windows 2019. When trying to test the new BHG strings in the ci-job-configs repo using the Puppet Repo Jenkins test harness it was obvious that there were issues with the parsing of the embedded "locale" string in the BHG name.
So since BHG already supports additional Beaker variables in the definition (see the use of the "user" variable for the French platform definitions to allow Windows use a localised Administrator name) it
makes sense to properly embed the "locale" definition here for the French and Japanese platforms.
This will allow the removal of the  windows2019_ja-64%7Blocale=ja%7D type string from the Puppet Agent CI job definitions.

(MAINT) Add locale to vmpooler Jap/French defs

---

lib/beaker-hostgenerator/data.rb
test/fixtures/generated/default/ciscon7k-64a
test/fixtures/generated/multiplatform/ciscon7k-64a-windows2019-6432-ciscon7k-64aulcdfm
test/fixtures/generated/osinfo-version-0/ciscon7k-64a
test/fixtures/generated/osinfo-version-1/ciscon7k-64a

tried to run the test generation rake task to update tests, but got a ton of what seems like extra stuff.
For instance, these are some of the files created:
```
test/fixtures/generated/osinfo-version-1/ubuntu1810-64aulcdfm
test/fixtures/generated/osinfo-version-1/vro6-64a
test/fixtures/generated/osinfo-version-1/vro7-64u
test/fixtures/generated/osinfo-version-1/vro71-64l
test/fixtures/generated/osinfo-version-1/vro73-64c
test/fixtures/generated/osinfo-version-1/vro74-64d
test/fixtures/generated/osinfo-version-1/windows10_1511-64u
test/fixtures/generated/osinfo-version-1/windows10_1607-64l
test/fixtures/generated/osinfo-version-1/windows10_1809-64c
```
@smcelmurry I assume I'm just missing something silly, or executing this wrong?

(QENG-7199) add cisco-n7k to data

---

lib/beaker-hostgenerator/data.rb
test/fixtures/generated/default/redhatfips7-64aulcdfm
test/fixtures/generated/multiplatform/redhatfips7-64aulcdfm-sles10-32-redhatfips7-64a
test/fixtures/generated/multiplatform/sles10-32a-redhatfips7-64-sles10-32aulcdfm
test/fixtures/generated/osinfo-version-0/redhatfips7-64aulcdfm
test/fixtures/generated/osinfo-version-1/redhatfips7-64aulcdfm

Now that we have a redhatfips7 tarball, this changes hostgenerator to use the redhatfips-7-x86_64 platform rather than el-7-x86_64.

(PE-27037) Use redhatfips-7-x86_64 for fips platform

---

beaker-hostgenerator.gemspec

The markdown down gem requires activesupport, which in
the newest version (6), loses support for Rubies below
2.5. There's no need for the markdown gem, so we'll
remove it rather than be forced to push up Ruby versions
at this time.
Ref: https://github.com/puppetlabs/beaker-puppet/pull/124

(MAINT) remove markdown requirement

---

lib/beaker-hostgenerator/data.rb
test/fixtures/generated/environment_variable_tests/pe_version_and_pe_family/centos6-32a
test/fixtures/generated/environment_variable_tests/pe_version_and_pe_family_no_upgrade/centos6-32a
test/fixtures/generated/environment_variable_tests/pe_version_and_pe_family_upgrade_only/centos6-32a

This commit replaces usage of enterprise.delivery.puppetlabs.net (aka saturn)
with Artifactory so that we can ultimately decommission it.

(RE-12859) Migrate from enterprise.delivery.puppetlabs.net to Artifactory

---

lib/beaker-hostgenerator/data.rb
spec/beaker-hostgenerator/generator_spec.rb

Update pe_dir() to return master path for versions > 2019.4

PE-27608 Update for master branch

---

lib/beaker-hostgenerator/data.rb
spec/beaker-hostgenerator/generator_spec.rb

In order for PEZ builds to be located correctly we need to add in some
logic. This PR adds to the Master branch logic by looking at the tarball
string and seeing if it is a PEZ tarball. If so point the pe_dir to the
feature directory, where the PEZ tarballs are put.

(PE-27608) Master branch PEZ logic

---

lib/beaker-hostgenerator/data.rb
spec/beaker-hostgenerator/generator_spec.rb

Required to keep some internal PE testing from breaking.

(maint) Update PE master version

---

lib/beaker-hostgenerator/data.rb

This switches from generic/debian10 to debian/buster64. This is the official box and thus closer to what should be expected by end users.

Use debian/buster64 for Vagrant

---

lib/beaker-hostgenerator/data.rb

The package `apt-transport-https` does not look present on old docker images.
We have debian8 and debian9 jobs that are failing with message: `The method driver /usr/lib/apt/methods/https could not be found.`
Details :
https://github.com/voxpupuli/puppet-nodejs/pull/416

install apt-transport-https on debian 8 and debian 9

---

lib/beaker-hostgenerator/data.rb

This ensures the en_US.UTF-8 locale is present which is very commonly used. This doesn't go as far as the Debian images, which install locales-all.

Install glibc-langpack-en on CentOS 8

---

lib/beaker-hostgenerator/data.rb
test/fixtures/generated/default/redhat8-AARCH64a
test/fixtures/generated/multiplatform/redhat6-64a-redhat8-AARCH64-redhat6-64aulcdfm
test/fixtures/generated/multiplatform/redhat8-AARCH64a-redhat6-64-redhat8-AARCH64aulcdfm
test/fixtures/generated/osinfo-version-0/redhat8-AARCH64a
test/fixtures/generated/osinfo-version-1/redhat8-AARCH64a

The arm64 and aarch64 targets are interchangeable, so I followed the
example of redhat7. Set the vmpooler template to x86_64 as we're going
to cross-compile packages.

(IMAGES-1230) Add support for RedHat 8 ARM64

---

lib/beaker-hostgenerator/data.rb
lib/beaker-hostgenerator/hypervisor/vagrant.rb
test/fixtures/generated/default/fedora32-64aulcdfm-vagrant

Previously it genereated fedora/31cloud-base but this needs to be 
fedora/31-cloud-base.

Add Fedora 32 + fix Fedora Vagrant box name

---

lib/beaker-hostgenerator/data.rb
spec/beaker-hostgenerator/generator_spec.rb

The master branch of enterprise-dist is now 2019.8.x, so the only thing we need to special-case is setting pe_dir for 2021 to 'main'.

(maint) Update for removal of enterprise-dist master

---

lib/beaker-hostgenerator/data.rb
spec/beaker-hostgenerator/generator_spec.rb

The previous commit omitted the case when the version contains 'pez' and not 'PEZ'.

(maint) Fix for PEZ builds

---

lib/beaker-hostgenerator/data.rb

Even though no offical packages have been built by Puppet, it still makes sense to be able to generate a definition.

Add Fedora 33 support

---

CODEOWNERS

This updates the existing codeowners file to be empty. We are planning
to transfer this repository to voxpupuli, and Codeowners files do not
currently support referencing teams from organizations that do not also
own the repo. That means that `@puppetlabs/beaker` will not reference
anything once we transfer the repo. Further, none of the members of that
team are actively working with this repo.

(maint) Remove existing codeowners

---

lib/beaker-hostgenerator/parser.rb

This fixes output like this in our GitHub Actions test runs:
`/home/runner/work/puppet-jira/puppet-jira/vendor/bundle/ruby/2.7.0/gems/beaker-hostgenerator-1.2.10/lib/beaker-hostgenerator/parser.rb:78: warning: URI.unescape is obsolete`

parser: replace obsolete URI.decode with CGI.unescape

---

lib/beaker-hostgenerator/data.rb
test/fixtures/generated/default/osx11-64f
test/fixtures/generated/multiplatform/osx11-64f-redhat7-POWER-osx11-64l
test/fixtures/generated/multiplatform/redhat7-POWERaulcdfm-osx11-64-redhat7-POWERa
test/fixtures/generated/osinfo-version-0/osx11-64f
test/fixtures/generated/osinfo-version-1/osx11-64f

Related to : https://github.com/puppetlabs/puppet-agent/pull/2081

Modify osx11.2 to osx11

---

lib/beaker-hostgenerator/data.rb

FWIW I cannot run the `generate:fixtures` rake task anymore, it fails at `fedora-19-i386`, might be related to the Fedora changes?
```
rake aborted!
TypeError: no implicit conversion of nil into Hash
/home/gabi/.rvm/gems/ruby-2.6.3/gems/activesupport-6.1.3.1/lib/active_support/core_ext/hash/deep_merge.rb:24:in `merge!'
/home/gabi/.rvm/gems/ruby-2.6.3/gems/activesupport-6.1.3.1/lib/active_support/core_ext/hash/deep_merge.rb:24:in `deep_merge!'
/home/gabi/repo/beaker-hostgenerator/lib/beaker-hostgenerator/data.rb:1961:in `get_platform_info'
/home/gabi/repo/beaker-hostgenerator/lib/beaker-hostgenerator/hypervisor.rb:97:in `block in base_generate_node'
/home/gabi/repo/beaker-hostgenerator/lib/beaker-hostgenerator/hypervisor.rb:96:in `map' …
```

Add support for el-8-ppc64le

---

lib/beaker-hostgenerator/data.rb
test/fixtures/generated/default/fedora34-64c
test/fixtures/generated/multiplatform/fedora34-64c-windows2012r2_fr-64-fedora34-64d
test/fixtures/generated/multiplatform/windows2012r2_fr-64d-fedora34-64-windows2012r2_fr-64c
test/fixtures/generated/osinfo-version-0/fedora34-64c
test/fixtures/generated/osinfo-version-1/fedora34-64c

I generated the fixtures without the changes from https://github.com/voxpupuli/beaker-hostgenerator/pull/209, and without the `github_changelog_generator` gem installed.

Add Fedora 34 support

---

lib/beaker-hostgenerator/data.rb
lib/beaker-hostgenerator/generator.rb
lib/beaker-hostgenerator/hypervisor.rb
lib/beaker-hostgenerator/hypervisor/abs.rb
lib/beaker-hostgenerator/hypervisor/docker.rb
lib/beaker-hostgenerator/hypervisor/unknown.rb
lib/beaker-hostgenerator/hypervisor/vagrant.rb
lib/beaker-hostgenerator/hypervisor/vmpooler.rb
lib/beaker-hostgenerator/util.rb

github-changelog-generator depends on activesupport which defines `Hash#deep_merge` methods that behave differently and conflict with the ones from the `deep_merge` gem. Use the recommended way of avoiding this conflict, as per the `deep_merge` documentation.[1]
Also, revert the changes from #209 which cause unexpected behavior with generated fixtures.
[1] https://github.com/danielsdeleo/deep_merge#using-deep_merge-in-rails

Avoid activesupport deep_merge conflict

---

lib/beaker-hostgenerator/hypervisor/docker.rb
test/fixtures/per-host-settings/docker-regex-validation.yaml
test/fixtures/per-host-settings/every-hypervisor.yaml

Prior to this, asking for oracle7-64 via Docker would fail due to the Docker image being named `oraclelinux` instead of just `oracle`.
A test was also added to ensure that the regex substitutions in docker.rb are working as expected.
This PR builds atop #214

Fix oracle image name

---

lib/beaker-hostgenerator/hypervisor/docker.rb
test/fixtures/per-host-settings/every-hypervisor.yaml

Prior to this, asking for a `centos8-64` host while running Beaker on a machine with an ARM processor such the M1 baesd Macs would pull the ARM version of CentOS instead of the x86-64 based one.

Ensure amd64 containers are pulled when needed

---

beaker-hostgenerator.gemspec
spec/helpers.rb

This was only used in tests, but there it really isn't needed.

Remove stringify-hash as a dependency

---

lib/beaker-hostgenerator/hypervisor/abs.rb

I missed this in my previous PR, only added vmpooler support initially.

Add ABS support for Rocky and Alma 8

---

lib/beaker-hostgenerator/data.rb
test/fixtures/generated/default/redhat9-64l
test/fixtures/generated/multiplatform/cisco_ios_c4507r-HWa-redhat9-64-cisco_ios_c4507r-HWaulcdfm
test/fixtures/generated/multiplatform/redhat9-64l-cisco_ios_c4507r-HW-redhat9-64f
test/fixtures/generated/osinfo-version-0/redhat9-64l
test/fixtures/generated/osinfo-version-1/redhat9-64l

A companion PR to https://github.com/voxpupuli/beaker/pull/1719

(IMAGES-1323) Adds RedHat 9 support

---

lib/beaker-hostgenerator/data.rb
test/fixtures/generated/default/archlinuxrolling-64a
test/fixtures/generated/default/archlinuxrolling-64c
test/fixtures/generated/default/archlinuxrolling-64l
test/fixtures/generated/default/archlinuxrolling-64u

This is incomplete since it's lacking tests, but I'm also unsure how if https://github.com/voxpupuli/modulesync_config/blob/4d4be4b600632c2fda96dde7f9ee53b4d248e078/moduleroot/spec/acceptance/nodesets/archlinux-2-x64.yml.erb#L12-L13 needs to be here as well.

Add Arch Linux support

---

lib/beaker-hostgenerator/data.rb

CentOS Linux 8 went End Of Life at the end of 2021 and at the end of January it will disappear from the mirrors. Stream is the supported replacement. By using the Vagrant box and container image it should mean most testing will not notice the difference.

Use CentOS Stream 8 instead of CentOS Linux 8

---

lib/beaker-hostgenerator/data.rb

This is not available in the minimal CentOS 8 Stream containers and specinfra relies on this for the hostname -f command to determine the FQDN.
Fixes: a4bdd3b3c51ccc65d6e75a9fa245a2f240b0d12d

Install hostname on CentOS 8 Stream in docker

---

lib/beaker-hostgenerator/data.rb
test/fixtures/generated/default/ubuntu2204-64l
test/fixtures/generated/default/ubuntu2204-AARCH64d
test/fixtures/generated/default/ubuntu2204-POWERc
test/fixtures/generated/multiplatform/ubuntu2204-64l-windows2008-64-ubuntu2204-64f
test/fixtures/generated/multiplatform/ubuntu2204-AARCH64d-vro73-64-ubuntu2204-AARCH64c
test/fixtures/generated/multiplatform/ubuntu2204-POWERc-vro74-64-ubuntu2204-POWERd
test/fixtures/generated/osinfo-version-0/ubuntu2204-64l
test/fixtures/generated/osinfo-version-0/ubuntu2204-AARCH64d
test/fixtures/generated/osinfo-version-0/ubuntu2204-POWERc
test/fixtures/generated/osinfo-version-1/ubuntu2204-64l
test/fixtures/generated/osinfo-version-1/ubuntu2204-AARCH64d
test/fixtures/generated/osinfo-version-1/ubuntu2204-POWERc

Note:
```
bundle exec rake generate:fixtures 
```
generates tons of new files and changes. I only include the relevant changes for this PR

Add Ubuntu 22.04

---

lib/beaker-hostgenerator/data.rb
test/fixtures/generated/default/fedora36-64f
test/fixtures/generated/default/windows11ent-64c
test/fixtures/generated/multiplatform/fedora19-64u-windows11ent-64-fedora19-64m
test/fixtures/generated/multiplatform/fedora36-64f-windows2012r2_fr-6432-fedora36-64l
test/fixtures/generated/multiplatform/windows11ent-64c-fedora19-64-windows11ent-64d
test/fixtures/generated/multiplatform/windows2012r2_fr-6432aulcdfm-fedora36-64-windows2012r2_fr-6432a
test/fixtures/generated/osinfo-version-0/fedora36-64f
test/fixtures/generated/osinfo-version-0/windows11ent-64c
test/fixtures/generated/osinfo-version-1/fedora36-64f
test/fixtures/generated/osinfo-version-1/windows11ent-64c

Supercedes [this PR](https://github.com/voxpupuli/beaker-hostgenerator/pull/252) while we wait for macOS M1 testing infrastructure to become available.
041996359d282054940a897cb148a7c1d6eddbcf is in response to [this comment](https://github.com/voxpupuli/beaker-hostgenerator/pull/252#discussion_r897227461) from @ekohl

Add Windows 11 Enterprise, Fedora 36

---

lib/beaker-hostgenerator/data.rb
test/fixtures/generated/default/osx11-ARM64u
test/fixtures/generated/default/osx12-ARM64c
test/fixtures/generated/multiplatform/debian8-64c-osx12-ARM64-debian8-64d
test/fixtures/generated/multiplatform/debian9-64f-osx11-ARM64-debian9-64l
test/fixtures/generated/multiplatform/osx11-ARM64u-debian9-64-osx11-ARM64m
test/fixtures/generated/multiplatform/osx12-ARM64c-debian8-64-osx12-ARM64d
test/fixtures/generated/osinfo-version-0/osx11-ARM64u
test/fixtures/generated/osinfo-version-0/osx12-ARM64c
test/fixtures/generated/osinfo-version-1/osx11-ARM64u
test/fixtures/generated/osinfo-version-1/osx12-ARM64c

For both IMAGES-1297 and IMAGES-1378, adds support for macOS 11
(Big Sur) and 12 (Monterey) M1 (ARM64) platforms.

(IMAGES-1297) Adds macOS 11/12 M1 support

---

lib/beaker-hostgenerator/data.rb
lib/beaker-hostgenerator/hypervisor/vmpooler.rb
lib/beaker-hostgenerator/util.rb

This was only used for EL 4 and a specific platform version, which are EOL now.

Drop fixup_node implementation

---

lib/beaker-hostgenerator/data.rb

This is not available in the minimal CentOS 9 Stream containers and specinfra relies on this for the hostname -f command to determine the FQDN.
Fixes: b7fe509f83284e85875108a48603abdd13ff3434

Install hostname on CentOS 9 Stream in docker

---

lib/beaker-hostgenerator/data.rb
test/fixtures/generated/default/osx13-64aulcdfm
test/fixtures/generated/multiplatform/debian7-64d-osx13-64-debian7-64c
test/fixtures/generated/multiplatform/osx13-64aulcdfm-debian7-64-osx13-64a
test/fixtures/generated/osinfo-version-0/osx13-64aulcdfm
test/fixtures/generated/osinfo-version-1/osx13-64aulcdfm

Add macos-13-x86_64 (Ventura) support

(RE-14886) Add macos-13-x86_64 support

---

lib/beaker-hostgenerator/data.rb

the one on vagrant cloud is old and outdated

use centos stream 8 box from cloud.centos.org

---

lib/beaker-hostgenerator/parser.rb

StringScanner is used without a corresponding require.  The lack of this require breaks under Ruby 3.1 in some environments.

Fix missing include for `strscan`

---

lib/beaker-hostgenerator/data.rb
lib/beaker-hostgenerator/hypervisor/docker.rb
lib/beaker-hostgenerator/hypervisor/vmpooler.rb

The aim is to reduce duplication in the data class. Making it shorter and easier to maintain.

Move more data into hypervisor specific classes

---

lib/beaker-hostgenerator/hypervisor/docker.rb

Fixes:
```jsonl
{"stream":"Step 7/9 : RUN yum intall -y crontabs initscripts iproute openssl wget which sysvinit-tools tar ss"}
{"stream":"\n"}
{"stream":" ---\u003e Running in f1b3d7cc1eae\n"}
{"stream":"Loaded plugins: fastestmirror, ovl\n"}
{"stream":"\u001b[91mNo such command: intall. Please use /usr/bin/yum --help\n\u001b[0m"}
{"errorDetail":{"code":1,"message":"The command '/bin/sh -c yum intall -y crontabs initscripts iproute openssl wget which sysvinit-tools tar ss' returned a non-zero code: 1"},"error":"The command '/bin/sh -c yum intall -y crontabs initscripts iproute openssl wget which sysvinit-tools tar ss' returned a non-zero code: 1"}
```

Fix typo in yum command

---

lib/beaker-hostgenerator/hypervisor/abs.rb

This commit moves abs template logic to the hypervisor just like what 2b97ea7 did but for abs instead of vmpooler.

Move abs template logic to hypervisor

---

lib/beaker-hostgenerator/hypervisor/docker.rb
test/fixtures/per-host-settings/every-hypervisor.yaml

Install iproute2. This provides `ss`:
https://packages.debian.org/bookworm/amd64/iproute2/filelist This is used by serverspec to check for open ports. This is probably not the best space because it's docker specific, but it will fix our tests.

Debian: Install iproute2

---

lib/beaker-hostgenerator/data.rb
lib/beaker-hostgenerator/hypervisor/docker.rb
test/fixtures/per-host-settings/docker-regex-validation.yaml

Currently testing in https://github.com/voxpupuli/puppet-yum/pull/319. Also requires https://github.com/voxpupuli/puppet_metadata/pull/98

Add OracleLinux 8 & 9 support

---

lib/beaker-hostgenerator/data.rb
test/fixtures/generated/default/redhat9-AARCH64m
test/fixtures/generated/multiplatform/centos7-64a-redhat9-AARCH64-centos7-64aulcdfm
test/fixtures/generated/multiplatform/redhat9-AARCH64m-centos7-64-redhat9-AARCH64u
test/fixtures/generated/osinfo-version-0/redhat9-AARCH64m
test/fixtures/generated/osinfo-version-1/redhat9-AARCH64m

I'm not sure about all the places that the `abs` and `vmpooler` platform data keys are used, but was a bit confused because the `redhat8-AARCH64` specifies the x86 template name `redhat-8-x86_64`, is that a mistake? https://github.com/voxpupuli/beaker-hostgenerator/blob/da8ac9a25030480925b79a84a34444d7f9d14970/lib/beaker-hostgenerator/data.rb#L348
So for the new platform's `vmpooler` key I used the expected name that we would use in vmpooler for that platform, is that correct? Or should that key just be omitted?
**EDIT**: Ah it looks like those keys related to the hypervisor gem. The above definitely seems like a bug per:
```
> beaker-hostgenerator redhat8-AARCH64 --hypervisor vmpooler
---
HOSTS:
redhat8-AARCH64-1:
platform: el-8-aarch64
template: redhat-8-x86_64
hypervisor: vmpooler …
```

(RE-15156) Add redhat-9-arm64 support

---

test/fixtures/generated/default/ubuntu2204-AARCH64m
test/fixtures/generated/multiplatform/ubuntu2204-AARCH64m-windows2008r2-6432-ubuntu2204-AARCH64u
test/fixtures/generated/multiplatform/windows2008r2-6432aulcdfm-ubuntu2204-AARCH64-windows2008r2-6432a
test/fixtures/generated/osinfo-version-0/ubuntu2204-AARCH64m
test/fixtures/generated/osinfo-version-1/ubuntu2204-AARCH64m

I'm not sure if this is needed since there was some data added in https://github.com/voxpupuli/beaker-hostgenerator/pull/248 and released in [1.14.0](https://github.com/voxpupuli/beaker-hostgenerator/blob/master/CHANGELOG.md#1140-2022-05-30), but without any changes to data.rb, these were the fixtures generated with `bundle exec rake generate:fixtures`
Side note, it seems a bit odd that we don't set the template key for the ubuntu platforms here. This must be already be inserted by [beaker-abs](https://github.com/puppetlabs/beaker-abs), but I haven't gone looking

(RE-15206) Add ubuntu-2204-arm64 fixtures

---

lib/beaker-hostgenerator/data.rb
lib/beaker-hostgenerator/hypervisor/abs.rb
test/fixtures/generated/default/amazon2023-64d
test/fixtures/generated/multiplatform/amazon2023-64d-vro71-64-amazon2023-64c
test/fixtures/generated/multiplatform/vro71-64c-amazon2023-64-vro71-64d
test/fixtures/generated/osinfo-version-0/amazon2023-64d
test/fixtures/generated/osinfo-version-1/amazon2023-64d

This adds support for Amazon Linux 2023.
Additionally, because what is noted in this [AWS blog post](https://aws.amazon.com/blogs/aws/amazon-linux-2023-a-cloud-optimized-linux-distribution-with-long-term-support/) the change also makes Amazon Linux >= 2023 it's own platform moving forward, while Amazon Linux 1 & 2 use the previously used platforms (el-6 and el-7).
Specifically noting:
> Amazon Linux 2023 isn’t directly comparable to any specific Fedora release. The Amazon Linux 2023 GA version includes components from [Fedora 34, 35, and 36](https://getfedora.org/en/server/download/). Some of the components are the same as the components in Fedora, and some are modified. Other components more closely resemble the components in [CentOS Stream 9](https://centos.org/stream9/) or were …

Add amazon-2023-x86_64

---

lib/beaker-hostgenerator/data.rb
test/fixtures/generated/default/amazon2023-AARCH64aulcdfm
test/fixtures/generated/multiplatform/amazon2023-AARCH64aulcdfm-solaris114-64-amazon2023-AARCH64a
test/fixtures/generated/multiplatform/solaris114-64f-amazon2023-AARCH64-solaris114-64l
test/fixtures/generated/osinfo-version-0/amazon2023-AARCH64aulcdfm
test/fixtures/generated/osinfo-version-1/amazon2023-AARCH64aulcdfm

So sorry I meant to do this in https://github.com/voxpupuli/beaker-hostgenerator/pull/333. It'll be the last for a while.

Add amazon2023-AARCH64

---

lib/beaker-hostgenerator/hypervisor/abs.rb
lib/beaker-hostgenerator/hypervisor/vmpooler.rb

When passing an unknown hostspec the platform is unknown. Using the safe operator avoids calling nil.gsub

Use the safe operator to avoid crashing

---

lib/beaker-hostgenerator/data.rb
lib/beaker-hostgenerator/hypervisor/abs.rb
test/fixtures/generated/default/aix73-POWERa
test/fixtures/generated/multiplatform/aix73-POWERa-archlinux-64-aix73-POWERaulcdfm
test/fixtures/generated/multiplatform/archlinux-64f-aix73-POWER-archlinux-64l
test/fixtures/generated/osinfo-version-0/aix73-POWERa
test/fixtures/generated/osinfo-version-1/aix73-POWERa

It's worth noting that I intentionally left off the `packaging_platform` value override for 7.3 that was previously done for 7.2. I think that the packaging platform should default to same version, but if it needs overridden, then that can simply be done at build time.

Add aix73-power

---

lib/beaker-hostgenerator/data.rb
test/fixtures/generated/default/redhat9-POWERf
test/fixtures/generated/multiplatform/amazon6-64a-redhat9-POWER-amazon6-64aulcdfm
test/fixtures/generated/multiplatform/redhat9-POWERf-amazon6-64-redhat9-POWERl
test/fixtures/generated/osinfo-version-0/redhat9-POWERf
test/fixtures/generated/osinfo-version-1/redhat9-POWERf

It's worth noting that I intentionally left off the CPU generation for the `template` value starting with RHEL9 on Power. This aligns with the format used for AIX, plus we don't specify multiple CPU generations for any vendor/architecture.

Add redhat9-power

---

lib/beaker-hostgenerator/data.rb
lib/beaker-hostgenerator/hypervisor/abs.rb
test/fixtures/generated/default/osx14-64aulcdfm
test/fixtures/generated/default/osx14-ARM64a
test/fixtures/generated/multiplatform/osx14-64aulcdfm-sles11-32-osx14-64a
test/fixtures/generated/multiplatform/osx14-ARM64a-redhat9-POWER-osx14-ARM64aulcdfm
test/fixtures/generated/multiplatform/redhat9-POWERa-osx14-ARM64-redhat9-POWERaulcdfm
test/fixtures/generated/multiplatform/sles11-32a-osx14-64-sles11-32aulcdfm
test/fixtures/generated/osinfo-version-0/osx14-64aulcdfm
test/fixtures/generated/osinfo-version-0/osx14-ARM64a
test/fixtures/generated/osinfo-version-1/osx14-64aulcdfm
test/fixtures/generated/osinfo-version-1/osx14-ARM64a

Of note, starting with osx14 the macos os data is added to `generate_osinfo`, so the `template` key is not present using the default vmpooler hypervisor. The `template` key for osx/macos is now set appropriately in the abs hypervisor. os data for previous osx versions is unchanged.

Add osx14-64 and osx14-ARM64 support

---

lib/beaker-hostgenerator/hypervisor/docker.rb

cronie is a weak dependency of crontabs, and while CentOS and RHEL install weak dependencies by default, other EL systems do not (so much for compatibility, huh?).
install cronie explicitly, to avoid "Could not find a suitable provider for cron" errors on those EL systems.

explicitly install cronie on EL8+

---

lib/beaker-hostgenerator/data.rb
lib/beaker-hostgenerator/hypervisor/abs.rb
test/fixtures/generated/default/amazon2023-AARCH64aulcdfm
test/fixtures/generated/multiplatform/amazon2023-AARCH64aulcdfm-solaris114-64-amazon2023-AARCH64a
test/fixtures/generated/multiplatform/solaris114-64f-amazon2023-AARCH64-solaris114-64l
test/fixtures/generated/osinfo-version-0/amazon2023-AARCH64aulcdfm
test/fixtures/generated/osinfo-version-1/amazon2023-AARCH64aulcdfm

Updated data.rb in host-generator to use 'aarch64' like it is using everywhere in project

(PA-5948) Update host generator to use aarch64 for amazon linux

---

lib/beaker-hostgenerator/data.rb

Fix rhel9 power ABS name

---

lib/beaker-hostgenerator/data.rb

Previously, Puppet tested Red Hat Enterprise Linux 7 packages against Amazon Linux 2, assuming they were binary-compatible. This commit updates beaker-hostgenerator to map AL2 packages to AL2 testing machines. (Note: AL2 is referred to in Vanagon and ABS as Amazon Linux 7, in reference to the assumed compatibility with RHEL7).

Update Amazon Linux 2 bindings

---

lib/beaker-hostgenerator/data.rb

In 4112690, I mapped Amazon Linux 2 (both x86_64 and AARCH64) to their respective ABS/Vanagon targets. This was incorrect, as AL2 x86_64 is still built on Red Hat Enterprise Linux 7.
This commit partially reverts that change and re-adds AL2 x86_64 to be built on RHEL 7.

Use Red Hat 7 for Amazon Linux 2 x86_64

---

lib/beaker-hostgenerator/data.rb
test/fixtures/generated/default/amazon2-AARCH64f
test/fixtures/generated/default/amazon2-AARCH64m
test/fixtures/generated/multiplatform/amazon2-AARCH64f-solaris11-64-amazon2-AARCH64l
test/fixtures/generated/multiplatform/amazon2-AARCH64m-solaris11-32-amazon2-AARCH64u
test/fixtures/generated/multiplatform/solaris11-32l-amazon2-AARCH64-solaris11-32f
test/fixtures/generated/multiplatform/solaris11-64d-amazon2-AARCH64-solaris11-64c
test/fixtures/generated/osinfo-version-0/amazon2-AARCH64f
test/fixtures/generated/osinfo-version-0/amazon2-AARCH64m
test/fixtures/generated/osinfo-version-1/amazon2-AARCH64f
test/fixtures/generated/osinfo-version-1/amazon2-AARCH64m

Amazon 7 is an implementation detail, the actual OS is Amazon 2:
https://aws.amazon.com/amazon-linux-2 This adds a new target amazon2-AARCH64,
whose ABS template remains the same (amazon-7-aarch64), but platform is
different:
❯ bundle exec beaker-hostgenerator amazon2-AARCH64a --hypervisor abs
---
HOSTS:
amazon2-AARCH64-1:
platform: amazon-2-aarch64
template: amazon-7-arm64
hypervisor: abs
roles:
- agent
CONFIG: {}
❯ bundle exec beaker-hostgenerator amazon7-AARCH64a --hypervisor abs
---
HOSTS:
amazon7-AARCH64-1:
platform: amazon-7-aarch64
hypervisor: abs
template: amazon-7-arm64
roles:
- agent
CONFIG: {}
The `template` is what we request from ABS. The `platform` is what beaker uses
when constructing `Beaker::Platform.new` and allows tests to introspect the
platform they're running on, …

Add Amazon 2

---

lib/beaker-hostgenerator/data.rb
test/fixtures/per-host-settings/vagrant-hypervisor.yaml

I added tests to #353 to see if that does what we need, not sure proper etiquette here, if we want me to PR into the other branch then merge that one?

Use latest CentOS boxes instead of specific dates

---

lib/beaker-hostgenerator/data.rb
test/fixtures/generated/default/almalinux9-AARCH64d
test/fixtures/generated/default/rocky9-AARCH64a
test/fixtures/generated/multiplatform/almalinux9-AARCH64d-sles12-S390X-almalinux9-AARCH64c
test/fixtures/generated/multiplatform/rocky9-AARCH64a-sles11-32-rocky9-AARCH64aulcdfm
test/fixtures/generated/multiplatform/sles11-32d-rocky9-AARCH64-sles11-32c
test/fixtures/generated/multiplatform/sles12-S390Xa-almalinux9-AARCH64-sles12-S390Xaulcdfm
test/fixtures/generated/osinfo-version-0/almalinux9-AARCH64d
test/fixtures/generated/osinfo-version-0/rocky9-AARCH64a
test/fixtures/generated/osinfo-version-1/almalinux9-AARCH64d
test/fixtures/generated/osinfo-version-1/rocky9-AARCH64a

Current Behaviour: For Rocky 9 and Almalinux9 ARM we get template as `rocky-9-aarch64` and `almalinux-9-aarch64` respectively.
```
bundle exec beaker-hostgenerator redhat7-64m-rocky9-AARCH64a --hypervisor abs          
---
HOSTS:
redhat7-64-1:
platform: el-7-x86_64
hypervisor: abs
template: redhat-7-x86_64
roles:
- agent
- master
rocky9-AARCH64-1:
platform: el-9-aarch64
hypervisor: abs
template: rocky-9-aarch64
roles:
- agent
CONFIG: {}
```
Expected behaviour: We need template name as `rocky-9-arm64` and `almalinux-9-arm64` to fetch VMs with ABS.
Result tested on local:
```
bundle exec beaker-hostgenerator --hypervisor abs redhat7-64m-almalinux9-AARCH64a-rocky9-AARCH64a
---
HOSTS:
redhat7-64-1:
platform: el-7-x86_64
hypervisor: abs
template: redhat-7-x86_64
roles:
- agent
- master …
```

Fix template name for rocky9 and almalinux9 arm

---

lib/beaker-hostgenerator/data.rb
test/fixtures/generated/default/oracle9-AARCH64l
test/fixtures/generated/multiplatform/opensuse42-32u-oracle9-AARCH64-opensuse42-32m
test/fixtures/generated/multiplatform/oracle9-AARCH64l-opensuse42-32-oracle9-AARCH64f
test/fixtures/generated/osinfo-version-0/oracle9-AARCH64l
test/fixtures/generated/osinfo-version-1/oracle9-AARCH64l

This is related to https://perforce.atlassian.net/browse/RE-16481

Add support for oracle9-aarch64

---

lib/beaker-hostgenerator/hypervisor.rb

This adds support for a `docker_podman` hypervisor. it will call the default docker implementation at the moment. See https://github.com/voxpupuli/gha-puppet/pull/48 for context.

Support different container implementations from beaker-docker

---

lib/beaker-hostgenerator/data.rb
test/fixtures/generated/default/windowsfips2016-64u
test/fixtures/generated/multiplatform/fedora28-64d-windowsfips2016-64-fedora28-64c
test/fixtures/generated/multiplatform/windowsfips2016-64u-fedora28-64-windowsfips2016-64m
test/fixtures/generated/osinfo-version-0/windowsfips2016-64u
test/fixtures/generated/osinfo-version-1/windowsfips2016-64u

This PR is to add support for windowsfips 2016.
Before:
```
bundle exec beaker-hostgenerator redhat8-64mcd-windowsfips2016-64f
---
HOSTS:
redhat8-64-1:
platform: el-8-x86_64
hypervisor: vmpooler
template: redhat-8-x86_64
roles:
- agent
- master
- dashboard
- database
windowsfips2016-64-1:
hypervisor: vmpooler
roles:
- agent
- frictionless
```
With this PR:
```
bundle exec beaker-hostgenerator redhat8-64mcd-windowsfips2016-64f       
---
HOSTS:
redhat8-64-1:
platform: el-8-x86_64
hypervisor: vmpooler
template: redhat-8-x86_64
roles:
- agent
- master
- dashboard
- database
windowsfips2016-64-1:
platform: windows-2016-64
packaging_platform: windowsfips-2016-x64
ruby_arch: x64
template: win-2016-fips-x86_64
hypervisor: vmpooler
roles:
- agent
- frictionless
```

Add support for windowsfips 2016 x64

---

beaker-hostgenerator.gemspec

added `skip-changelog` because that's just a dev dependency

rspec-its: Allow 2.x

---

lib/beaker-hostgenerator/data.rb
test/fixtures/generated/default/osx15-64aulcdfm
test/fixtures/generated/multiplatform/osx15-64aulcdfm-rocky9-AARCH64-osx15-64a
test/fixtures/generated/multiplatform/rocky9-AARCH64a-osx15-64-rocky9-AARCH64aulcdfm
test/fixtures/generated/osinfo-version-0/osx15-64aulcdfm
test/fixtures/generated/osinfo-version-1/osx15-64aulcdfm

(PA-6776): Added osx-15-x86_64 support.

---

lib/beaker-hostgenerator/data.rb
test/fixtures/generated/default/windows2025_ent-64d
test/fixtures/generated/multiplatform/fedora24-32c-windows2025_ent-64-fedora24-32d
test/fixtures/generated/multiplatform/windows2025_ent-64d-fedora24-32-windows2025_ent-64c
test/fixtures/generated/osinfo-version-0/windows2025_ent-64d
test/fixtures/generated/osinfo-version-1/windows2025_ent-64d

Added new platform for Windows Server 2025

Add new platform for windows server 2025

---

lib/beaker-hostgenerator/data.rb
test/fixtures/generated/default/windows2025-64d
test/fixtures/generated/multiplatform/fedora24-32c-windows2025-64-fedora24-32d
test/fixtures/generated/multiplatform/windows2025-64d-fedora24-32-windows2025-64c
test/fixtures/generated/osinfo-version-0/windows2025-64d
test/fixtures/generated/osinfo-version-1/windows2025-64d

Corrects the packaging_platform and naming convention for the Windows Server 2025 entry in beaker-hostgenerator.
- Changed packaging_platform from `windows-2025-x64` to `windows-2012-x64`
- Updated the platform name from `windows2025_ent-64` to a more accurate and consistent format
Context:
Support for Windows Server 2025 was initially added in PR #396, but it included incorrect values for packaging_platform and name.
This update ensures compatibility and aligns with expected standards for platform representation in test orchestration.
Refs: voxpupuli/beaker-hostgenerator#396

(PA-7442) Fix Windows Server 2025 platform entry in beaker-hostgenerator

---

lib/beaker-hostgenerator/data.rb
lib/beaker-hostgenerator/hypervisor/vagrant.rb

This first refactors Debian's Vagrant boxes to be added by the hypervisor. It then uses this to generate them in a loop. As a  last step it adds Debian 13 by running another loop.

Add Debian 13 support and make CentOS & Debian easier to maintain

---

lib/beaker-hostgenerator/hypervisor/docker.rb

There is no library path for Rocky 10
* `docker://docker.io/rockylinux:10` does not exist
* `docker://docker.io/rockylinux/rockylinux:10` does exist`
* `docker://quay.io/rockylinux/rockylinux:10` does exist`
https://github.com/voxpupuli/puppet-cvmfs/pull/224 shows use of this patch.

Use non library path for rocky 10
