lib/beaker-hostgenerator/data/vmpooler.rb
=> (MAINT) Fix arista4 spec string.

CHANGELOG.md
@joshcooper @kevpl @sschneid @colinPL @doug-rosser @justinstoller
=> (MAINT) Update Changelog for recent releases.

lib/beaker-hostgenerator/data/vmpooler.rb
Waiting for beaker PR1066 to get merged first
=> (BKR-706) Update Cisco platforms to match beaker

lib/beaker-hostgenerator/data.rb
Adding sles12-s390x. Waiting until other platforms are added to generate fixtures
=> (QENG-3815) Adding sles12-s390x

lib/beaker-hostgenerator/data.rb, test/fixtures/generated/default/windows2012r2_ja-6432a, test/fixtures/generated/default/windows2012r2_ja-64aulcdfm, test/fixtures/generated/multiplatform/centos5-64aulcdfm-windows2012r2_ja-6432-centos5-64a, test/fixtures/generated/multiplatform/centos6-32a-windows2012r2_ja-64-centos6-32aulcdfm, test/fixtures/generated/osinfo-version-0/windows2012r2_ja-6432a, test/fixtures/generated/osinfo-version-0/windows2012r2_ja-64aulcdfm, test/fixtures/generated/osinfo-version-1/windows2012r2_ja-6432a, test/fixtures/generated/osinfo-version-1/windows2012r2_ja-64aulcdfm
This commit adds the Japanese Windows 2012 R2 VMPooler template in preparation
of testing non-US English systems in Beaker.
=> (BKR-1013) Add Windows 2012R2 Japanese Template

lib/beaker-hostgenerator/data.rb, test/fixtures/generated/default/fedora26-64m, test/fixtures/generated/multiplatform/fedora26-64m-ubuntu1204-64-fedora26-64u, test/fixtures/generated/osinfo-version-0/fedora26-64m, test/fixtures/generated/osinfo-version-1/fedora26-64m
This commit adds the definition for the fedora 26 64 bit platform
=> (IMAGES-594) Add fedora 26

lib/beaker-hostgenerator/data.rb, test/fixtures/generated/default/ubuntu1804-64a, test/fixtures/generated/multiplatform/fedora22-32u-ubuntu1804-64-fedora22-32m, test/fixtures/generated/multiplatform/ubuntu1804-64a-fedora22-32-ubuntu1804-64aulcdfm, test/fixtures/generated/osinfo-version-0/ubuntu1804-64a, test/fixtures/generated/osinfo-version-1/ubuntu1804-64a
We've started work on imaging 18.04 for vmpooler - There is an open beaker PR [here](https://github.com/puppetlabs/beaker/pull/1502) to add the codename.
=> (IMAGES-754) Add the ubuntu1804-64 platform

lib/beaker-hostgenerator/data.rb, lib/beaker-hostgenerator/hypervisor.rb, lib/beaker-hostgenerator/hypervisor/docker.rb, test/fixtures/per-host-settings/every-hypervisor.yaml
This also copies in the docker image commands as used by Voxpupuli.
=> Add a docker hypervisor

CHANGELOG.md
Additionally, update it for previously missed releases. `1.1.10 - 1.1.13`
=> (maint) Update Changelog for version 1.1.14

CHANGELOG.md
Add panos platforms to changelog
=> (MAINT) Release notes for 1.1.15

beaker-hostgenerator.gemspec
Removed old description that was overwriting newer and better version.
=> (MAINT) Fix gemspec description

CHANGELOG.md
=> (maint) Update CHANGLOG.md for 1.1.18 release

lib/beaker-hostgenerator/data.rb, test/fixtures/generated/default/windows2016_fr-6432f, test/fixtures/generated/default/windows2016_fr-64d, test/fixtures/generated/multiplatform/centos5-64c-windows2016_fr-6432-centos5-64d, test/fixtures/generated/multiplatform/centos6-32d-windows2016_fr-64-centos6-32c, test/fixtures/generated/multiplatform/windows2016_fr-6432f-centos5-64-windows2016_fr-6432l, test/fixtures/generated/multiplatform/windows2016_fr-64d-centos6-32-windows2016_fr-64c, test/fixtures/generated/osinfo-version-0/windows2016_fr-6432f, test/fixtures/generated/osinfo-version-0/windows2016_fr-64d, test/fixtures/generated/osinfo-version-1/windows2016_fr-6432f, test/fixtures/generated/osinfo-version-1/windows2016_fr-64d
=> (IMAGES-1053) Add beaker-hostgenerator support for Windows2016 French x86_64

lib/beaker-hostgenerator/data.rb, test/fixtures/generated/default/redhatfips7-64aulcdfm, test/fixtures/generated/multiplatform/redhatfips7-64aulcdfm-sles10-32-redhatfips7-64a, test/fixtures/generated/multiplatform/sles10-32a-redhatfips7-64-sles10-32aulcdfm, test/fixtures/generated/osinfo-version-0/redhatfips7-64aulcdfm, test/fixtures/generated/osinfo-version-1/redhatfips7-64aulcdfm
Reverts puppetlabs/beaker-hostgenerator#162
=> Revert "(PE-27037) Use redhatfips-7-x86_64 for fips platform"

lib/beaker-hostgenerator/data.rb, test/fixtures/generated/default/windows2012r2fips-6432u, test/fixtures/generated/default/windows2012r2fips-64a, test/fixtures/generated/multiplatform/cumulus25-64u-windows2012r2fips-64-cumulus25-64m, test/fixtures/generated/multiplatform/cumulus25-64u-windows2012r2fips-6432-cumulus25-64m, test/fixtures/generated/multiplatform/debian6-32l-windows2012r2fips-64-debian6-32f, test/fixtures/generated/multiplatform/windows2012r2fips-6432u-cumulus25-64-windows2012r2fips-6432m, test/fixtures/generated/multiplatform/windows2012r2fips-64a-cumulus25-64-windows2012r2fips-64aulcdfm, test/fixtures/generated/multiplatform/windows2012r2fips-64a-debian6-32-windows2012r2fips-64aulcdfm, test/fixtures/generated/osinfo-version-0/windows2012r2fips-6432u, test/fixtures/generated/osinfo-version-0/windows2012r2fips-64a, test/fixtures/generated/osinfo-version-1/windows2012r2fips-6432u, test/fixtures/generated/osinfo-version-1/windows2012r2fips-64a
Add beaker-hostgenerator support for winfips-2012r2-x64
=> (IMAGES-1139) BHG support for winfips-2012r2-x64

lib/beaker-hostgenerator/data.rb, lib/beaker-hostgenerator/hypervisor/docker.rb
Replacement for https://github.com/voxpupuli/beaker-hostgenerator/pull/182
=> Add support for OpenSuSE 42 and 15

lib/beaker-hostgenerator/data.rb
This does at least make rake generate:fixtures work, but then the result is still not really what you'd expect.
=> Deal with nil when merging

lib/beaker-hostgenerator/data.rb
This copies the section from Debian 10 since it appears to require the same things.
=> Set up Debian 11 on Docker

lib/beaker-hostgenerator/data.rb, test/fixtures/generated/default/fedora37-64m, test/fixtures/generated/default/fedora38-64aulcdfm, test/fixtures/generated/multiplatform/fedora37-64m-windows2012r2_ja-64-fedora37-64u, test/fixtures/generated/multiplatform/fedora38-64aulcdfm-windows2012r2_wmf5-64-fedora38-64a, test/fixtures/generated/multiplatform/windows2012r2_ja-64a-fedora37-64-windows2012r2_ja-64aulcdfm, test/fixtures/generated/multiplatform/windows2012r2_wmf5-64aulcdfm-fedora38-64-windows2012r2_wmf5-64a, test/fixtures/generated/osinfo-version-0/fedora37-64m, test/fixtures/generated/osinfo-version-0/fedora38-64aulcdfm, test/fixtures/generated/osinfo-version-1/fedora37-64m, test/fixtures/generated/osinfo-version-1/fedora38-64aulcdfm
This is to allows Fedora 37 and Fedora 38 x64
=> Add fedora-37-x86_64 and fedora-38-x86_64

lib/beaker-hostgenerator/hypervisor/vagrant.rb
For AlmaLinux we want to pull:
* https://app.vagrantup.com/almalinux/boxes/9
* https://app.vagrantup.com/almalinux/boxes/8
=> Pull correct vagrant boxes for AlmaLinux

lib/beaker-hostgenerator/data.rb, test/fixtures/generated/default/fedora40-64l, test/fixtures/generated/multiplatform/fedora40-64l-windowsfips2012r2-64-fedora40-64f, test/fixtures/generated/multiplatform/windowsfips2012r2-64d-fedora40-64-windowsfips2012r2-64c, test/fixtures/generated/osinfo-version-0/fedora40-64l, test/fixtures/generated/osinfo-version-1/fedora40-64l
This PR adds support in beaker-hostgenerator for Fedora 40 image.
=> Add beaker-hostgenerator support for Fedora40-x86_64

Gemfile, Rakefile, beaker-hostgenerator.gemspec
This is now equal to all other gems we have.
=> cleanup voxpupli-rubocop setup

lib/beaker-hostgenerator/hypervisor/docker.rb, test/fixtures/per-host-settings/docker-regex-validation.yaml
Ref https://hub.docker.com/r/opensuse/leap/tags
=> Don't prepend amd64/ for opensuse images

lib/beaker-hostgenerator/data.rb
Created a new Fedora 41 template
=> Created a new Fedora 41 template

lib/beaker-hostgenerator/data.rb, test/fixtures/generated/default/redhat10-64f, test/fixtures/generated/multiplatform/archlinuxrolling-64l-redhat10-64-archlinuxrolling-64f, test/fixtures/generated/multiplatform/redhat10-64f-archlinuxrolling-64-redhat10-64l, test/fixtures/generated/osinfo-version-0/redhat10-64f, test/fixtures/generated/osinfo-version-1/redhat10-64f
=> Updated Redhat-10-beta 

lib/beaker-hostgenerator/data.rb, lib/beaker-hostgenerator/hypervisor/abs.rb, lib/beaker-hostgenerator/hypervisor/vmpooler.rb
Refactor SLES host definitions for easier management.
=> Use a loop for SLES
